2017-06-10 17:36:10 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Services could not be found.
Exception Attributes: array (
  'class' => 'Services',
  'plugin' => false,
  'prefix' => false,
  '_ext' => false,
)
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ControllerFactory.php(70): Cake\Http\ControllerFactory->missingController(Object(Cake\Http\ServerRequest))
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(90): Cake\Http\ControllerFactory->create(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-06-10 17:37:04 Error: [Cake\Controller\Exception\MissingActionException] Action ServicesController::signup() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ServicesController',
  'action' => 'signup',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-06-10 17:37:19 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\signup.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\signup.ctp',
)
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\View\View.php(592): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(623): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(125): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#17 {main}


2017-06-10 17:39:46 Error: [BadMethodCallException] Method post does not exist
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(12): Cake\Http\ServerRequest->__call('post', Array)
#1 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(12): Cake\Http\ServerRequest->post()
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->signup()
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#18 {main}


2017-06-10 17:50:02 Error: Fatal Error (1): Class 'App\Controller\TableRegister' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 17]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 17:50:02 Warning: Headers already sent in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php:17
2017-06-10 17:50:02 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\TableRegister' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 17
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 17:50:16 Error: Fatal Error (1): Class 'App\Controller\TableRegister' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 17]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 17:50:16 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\TableRegister' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 17
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 17)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 17:50:35 Error: Fatal Error (1): Class 'App\Controller\TableRegister' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 18]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 17:50:35 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\TableRegister' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 18
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 17:51:11 Error: Fatal Error (1): Class 'App\Controller\TableRegister' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 18]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 17:51:11 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\TableRegister' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 18
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 17:51:55 Error: Fatal Error (1): Class 'App\Controller\TableRegister' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 18]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 17:51:55 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\TableRegister' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 18
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 17:51:56 Error: Fatal Error (1): Class 'App\Controller\TableRegister' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 18]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 17:51:56 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\TableRegister' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 18
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 17:52:28 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'meeat.user' doesn't exist
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(97): Cake\Database\Schema\Collection->_reflect('Column', 'user', Array, Object(Cake\Database\Schema\TableSchema))
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(63): Cake\Database\Schema\Collection->describe('user', Array)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(531): Cake\Database\Schema\CachedCollection->describe('user')
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(210): Cake\ORM\Table->getSchema()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(167): Cake\ORM\Query->addDefaultTypes(Object(Cake\ORM\Table))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1569): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(Cake\ORM\Table))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1171): Cake\ORM\Table->query()
#7 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(19): Cake\ORM\Table->find()
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->signup()
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#23 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#24 {main}


2017-06-10 18:00:24 Error: Fatal Error (4): syntax error, unexpected 'print_r' (T_STRING) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 20]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 18:00:24 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'print_r' (T_STRING) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 20
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 20)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 18:37:30 Error: [Cake\Controller\Exception\MissingActionException] Action ServicesController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ServicesController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-06-10 18:59:55 Error: Fatal Error (1): Class 'App\Controller\Uuid' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 18]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 18:59:55 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\Uuid' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 18
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:00:17 Error: Fatal Error (4): syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 7]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:00:17 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 7
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:00:38 Error: Fatal Error (4): syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 7]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:00:38 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 7
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:07:35 Error: Fatal Error (4): syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 7]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:07:35 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 7
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:07:38 Error: Fatal Error (4): syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 7]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:07:38 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'use' (T_USE), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 7
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:07:52 Error: Fatal Error (4): syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 8]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:07:52 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'class' (T_CLASS), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 8
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:08:05 Error: Fatal Error (1): Class 'App\Controller\String' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 19]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:08:05 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\String' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 19
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:21:01 Error: Fatal Error (4): syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 7]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:21:01 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 7
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:21:20 Error: Fatal Error (4): syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ',' or ';' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 7]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:21:20 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ',' or ';' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 7
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-10 19:22:03 Error: Fatal Error (1): Class 'App\Controller\Text' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 19]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-10 19:22:03 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\Text' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 19
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 07:32:01 Error: Fatal Error (1): Class 'App\Controller\Text' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 19]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 07:32:01 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\Text' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 19
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 07:45:21 Error: Fatal Error (1): Class 'App\Controller\Security' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 53]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 07:45:21 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\Security' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 53
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 53)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 07:45:41 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of Cake\ORM\Table given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 67 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 67
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 07:45:41 Error: [BadMethodCallException] Unknown method "errors"
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1714): Cake\ORM\Table->__call('errors', Array)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1714): Cake\ORM\Table->errors()
#2 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(67): Cake\ORM\Table->save(Object(Cake\ORM\Table))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->signup()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#19 {main}


2017-06-11 07:47:03 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 59]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 07:47:03 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'if' (T_IF) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 59
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 59)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 07:47:22 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 59]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 07:47:22 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'if' (T_IF) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 59
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 59)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 07:48:03 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of Cake\ORM\Table given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 68 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 68
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 07:48:03 Error: [BadMethodCallException] Unknown method "errors"
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1714): Cake\ORM\Table->__call('errors', Array)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1714): Cake\ORM\Table->errors()
#2 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(68): Cake\ORM\Table->save(Object(Cake\ORM\Table))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->signup()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#19 {main}


2017-06-11 07:49:22 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of Cake\ORM\Table given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 74 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 74
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 07:49:22 Error: [BadMethodCallException] Unknown method "errors"
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1714): Cake\ORM\Table->__call('errors', Array)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1714): Cake\ORM\Table->errors()
#2 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(74): Cake\ORM\Table->save(Object(Cake\ORM\Table))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->signup()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#19 {main}


2017-06-11 07:51:05 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 69]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 69
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 07:52:41 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 70]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 70
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 07:55:56 Error: Fatal Error (1): Class 'App\Controller\stdClass' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 70]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 07:55:56 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\stdClass' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 70
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 70)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 07:56:49 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 71]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 71
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 07:57:19 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 71]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 71
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:00:06 Error: Fatal Error (1): Call to undefined function App\Controller\php_info() in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 58]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:00:06 Error: [Cake\Error\FatalErrorException] Call to undefined function App\Controller\php_info() in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 58
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:00:29 Error: Fatal Error (1): Call to undefined function App\Controller\php_info() in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 58]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:00:29 Error: [Cake\Error\FatalErrorException] Call to undefined function App\Controller\php_info() in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 58
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:02:30 Error: Fatal Error (1): Class 'Cake\Utility\stdClass' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 72]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:02:30 Error: [Cake\Error\FatalErrorException] Class 'Cake\Utility\stdClass' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 72
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'Cake\\Uti...', 'C:\\xampp\\htdocs...', 72)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:02:47 Error: Fatal Error (1): Class 'App\Controller\stdClass' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 71]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:02:47 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\stdClass' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 71
Request URL: /services/signup
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 71)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:04:42 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 72]
Request URL: /services/signup
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::signup() - APP/Controller\ServicesController.php, line 72
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:24:11 Error: [BadMethodCallException] Unknown finder method "first"
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1174): Cake\ORM\Table->callFinder('first', Object(Cake\ORM\Query), Array)
#1 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(134): Cake\ORM\Table->find('first', Array)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->login()
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#18 {main}


2017-06-11 08:31:26 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::delete() must implement interface Cake\Datasource\EntityInterface, array given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 137 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 2064]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::delete() - CORE\src\ORM\Table.php, line 2064
App\Controller\ServicesController::login() - APP/Controller\ServicesController.php, line 137
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:31:26 Error: Fatal Error (1): Call to a member function isNew() on array in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 2120]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:31:26 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-11 08:31:26 Error: [Cake\Error\FatalErrorException] Call to a member function isNew() on array in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 2120
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 2120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:32:00 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 137]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:32:00 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 137
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 137)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:33:50 Error: Fatal Error (4): syntax error, unexpected '=>' (T_DOUBLE_ARROW) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 137]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:33:51 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '=>' (T_DOUBLE_ARROW) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 137
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 137)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:36:26 Error: Fatal Error (1): Call to a member function deleteAll() on boolean in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 138]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:36:26 Error: [Cake\Error\FatalErrorException] Call to a member function deleteAll() on boolean in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 138
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 138)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:39:03 Error: Fatal Error (1): Call to a member function deleteAll() on boolean in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 138]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:39:03 Error: [Cake\Error\FatalErrorException] Call to a member function deleteAll() on boolean in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 138
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 138)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:41:51 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 137]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::login() - APP/Controller\ServicesController.php, line 137
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:41:51 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::delete() must implement interface Cake\Datasource\EntityInterface, instance of stdClass given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 138 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 2064]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::delete() - CORE\src\ORM\Table.php, line 2064
App\Controller\ServicesController::login() - APP/Controller\ServicesController.php, line 138
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:41:51 Error: Fatal Error (1): Call to undefined method stdClass::isNew() in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 2120]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:41:51 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-11 08:41:51 Error: [Cake\Error\FatalErrorException] Call to undefined method stdClass::isNew() in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 2120
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 2120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:47:40 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 137]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::login() - APP/Controller\ServicesController.php, line 137
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:47:40 Error: Fatal Error (1): Call to a member function get() on boolean in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 139]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:47:40 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-11 08:47:40 Error: [Cake\Error\FatalErrorException] Call to a member function get() on boolean in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 139
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 139)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 08:55:52 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 137]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::login() - APP/Controller\ServicesController.php, line 137
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:55:52 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 141]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::login() - APP/Controller\ServicesController.php, line 141
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-11 08:55:52 Error: Fatal Error (1): Call to a member function delete() on boolean in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 142]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 08:55:52 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-11 08:55:52 Error: [Cake\Error\FatalErrorException] Call to a member function delete() on boolean in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 142
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 142)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 09:04:33 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(313): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1916): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1810): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1723): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->Cake\ORM\{closure}()
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(680): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1447): Cake\Database\Connection->transactional(Object(Closure))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1724): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#12 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(145): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->login()
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#23 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#24 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#29 {main}


2017-06-11 09:04:33 Warning: Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php line=822 in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 48]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:04:33 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 149]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE\src\Http\ResponseEmitter.php, line 149
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:04:33 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:04:33 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:05:58 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(313): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1916): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1810): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1723): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->Cake\ORM\{closure}()
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(680): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1447): Cake\Database\Connection->transactional(Object(Closure))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1724): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#12 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(151): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->login()
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#23 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#24 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#29 {main}


2017-06-11 09:05:58 Warning: Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php line=822 in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 48]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:05:58 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 149]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE\src\Http\ResponseEmitter.php, line 149
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:05:58 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:05:58 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:07:16 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(313): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1916): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1810): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1723): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->Cake\ORM\{closure}()
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(680): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1447): Cake\Database\Connection->transactional(Object(Closure))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php(1724): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#12 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(151): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->login()
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#23 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#24 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#26 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#27 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#28 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#29 {main}


2017-06-11 09:07:17 Warning: Warning (512): Unable to emit headers. Headers sent in file=C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php line=822 in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 48]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 48
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:07:17 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 149]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitStatusLine() - CORE\src\Http\ResponseEmitter.php, line 149
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 54
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:07:17 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 09:07:17 Warning: Warning (2): Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822) in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ResponseEmitter.php, line 181]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
header - [internal], line ??
Cake\Http\ResponseEmitter::emitHeaders() - CORE\src\Http\ResponseEmitter.php, line 181
Cake\Http\ResponseEmitter::emit() - CORE\src\Http\ResponseEmitter.php, line 55
Cake\Http\Server::emit() - CORE\src\Http\Server.php, line 105
[main] - ROOT\webroot\index.php, line 37



2017-06-11 10:16:24 Error: Fatal Error (1): Class 'App\Controller\App' not found in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 9]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 10:16:25 Error: [Cake\Error\FatalErrorException] Class 'App\Controller\App' not found in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 9
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Class 'App\\Cont...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-11 10:17:45 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 229]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-11 10:17:45 Error: [Cake\Error\FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 229
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 229)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-17 10:02:15 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 229]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-17 10:02:16 Error: [Cake\Error\FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 229
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 229)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-17 10:03:04 Error: Fatal Error (4): syntax error, unexpected end of file, expecting function (T_FUNCTION) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 229]
Request URL: /services/login
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-17 10:03:04 Error: [Cake\Error\FatalErrorException] syntax error, unexpected end of file, expecting function (T_FUNCTION) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 229
Request URL: /services/login
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 229)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-20 17:55:33 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 221]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-20 17:55:35 Error: [Cake\Error\FatalErrorException] syntax error, unexpected ')' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 221
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 221)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-20 17:57:15 Error: Fatal Error (4): syntax error, unexpected '}' in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 231]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-20 17:57:15 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}' in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 231
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 231)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-22 18:32:36 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 230]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 230
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:32:36 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of stdClass given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 243 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 243
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:32:36 Error: Fatal Error (1): Call to undefined method stdClass::errors() in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1714]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-22 18:32:37 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-22 18:32:37 Error: [Cake\Error\FatalErrorException] Call to undefined method stdClass::errors() in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 1714
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1714)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-22 18:34:09 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 230]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 230
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:34:09 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of stdClass given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 243 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 243
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:34:09 Error: Fatal Error (1): Call to undefined method stdClass::errors() in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1714]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-22 18:34:09 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-22 18:34:09 Error: [Cake\Error\FatalErrorException] Call to undefined method stdClass::errors() in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 1714
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1714)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-22 18:37:41 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 230]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 230
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:37:41 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of stdClass given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 243 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 243
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:37:41 Error: Fatal Error (1): Call to undefined method stdClass::errors() in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1714]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-22 18:37:41 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-22 18:37:41 Error: [Cake\Error\FatalErrorException] Call to undefined method stdClass::errors() in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 1714
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1714)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-22 18:38:58 Warning: Warning (2): Creating default object from empty value in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 230]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 230
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:38:58 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, instance of stdClass given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 243 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::UpdateProfile() - APP/Controller\ServicesController.php, line 243
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-06-22 18:38:58 Error: Fatal Error (1): Call to undefined method stdClass::errors() in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1714]
Request URL: /services/UpdateProfile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-06-22 18:38:58 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-06-22 18:38:58 Error: [Cake\Error\FatalErrorException] Call to undefined method stdClass::errors() in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 1714
Request URL: /services/UpdateProfile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 1714)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-06-26 11:34:20 Error: [Cake\Controller\Exception\MissingActionException] Action ServicesController::sociallogin() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ServicesController',
  'action' => 'sociallogin',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /services/sociallogin
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-06-26 11:34:20 Error: [Cake\Controller\Exception\MissingActionException] Action ServicesController::sociallogin() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ServicesController',
  'action' => 'sociallogin',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /services/sociallogin
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-06-26 11:34:49 Error: [Cake\Controller\Exception\MissingActionException] Action ServicesController::sociallogin() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ServicesController',
  'action' => 'sociallogin',
  'prefix' => '',
  'plugin' => false,
)
Request URL: /services/sociallogin
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#15 {main}


2017-07-24 17:05:47 Error: [PDOException] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'meeat.events' doesn't exist
Request URL: /services/eventsearch
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(327): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(283): Cake\Database\Connection->query('SELECT *, latit...')
#5 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(805): Cake\Database\Connection->execute('SELECT *, latit...')
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->eventsearch()
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#9 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#21 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#22 {main}


2017-07-29 12:46:57 Warning: Warning (4096): Argument 1 passed to Cake\ORM\Table::save() must implement interface Cake\Datasource\EntityInterface, null given, called in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 878 and defined in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1700]
Request URL: /services/eventimages
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Cake\ORM\Table::save() - CORE\src\ORM\Table.php, line 1700
App\Controller\ServicesController::eventimages() - APP/Controller\ServicesController.php, line 878
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 440
Cake\Http\ActionDispatcher::_invoke() - CORE\src\Http\ActionDispatcher.php, line 119
Cake\Http\ActionDispatcher::dispatch() - CORE\src\Http\ActionDispatcher.php, line 93
Cake\Http\BaseApplication::__invoke() - CORE\src\Http\BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE\src\Routing\Middleware\RoutingMiddleware.php, line 59
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE\src\Routing\Middleware\AssetMiddleware.php, line 88
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE\src\Error\Middleware\ErrorHandlerMiddleware.php, line 92
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
DebugKit\Middleware\DebugKitMiddleware::__invoke() - ROOT\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php, line 52
Cake\Http\Runner::__invoke() - CORE\src\Http\Runner.php, line 65
Cake\Http\Runner::run() - CORE\src\Http\Runner.php, line 51
Cake\Http\Server::run() - CORE\src\Http\Server.php, line 80
[main] - ROOT\webroot\index.php, line 37



2017-07-29 12:46:57 Error: Fatal Error (1): Call to a member function errors() on null in [C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php, line 1714]
Request URL: /services/eventimages
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-07-29 12:46:57 Warning: Headers already sent in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Debugger.php:822
2017-07-29 12:46:57 Error: [Cake\Error\FatalErrorException] Call to a member function errors() on null in C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Table.php on line 1714
Request URL: /services/eventimages
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 1714)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-07-29 14:07:05 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Images.event_id' in 'where clause'
Request URL: /services/eventinfo
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(313): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(1011): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(276): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(960): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(293): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(968): Cake\ORM\Query->toArray()
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->eventinfo()
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#26 {main}


2017-07-29 14:07:37 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Images.event_id' in 'where clause'
Request URL: /services/eventinfo
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(313): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(1011): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(276): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(960): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(293): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(968): Cake\ORM\Query->toArray()
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->eventinfo()
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#26 {main}


2017-07-29 14:08:22 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Images.id' in 'where clause'
Request URL: /services/eventinfo
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(39): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(174): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Connection.php(313): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Database\Query.php(213): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(1011): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(276): Cake\ORM\Query->_execute()
#7 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\ORM\Query.php(960): Cake\ORM\Query->_all()
#8 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(293): Cake\ORM\Query->all()
#9 C:\xampp\htdocs\meeat\src\Controller\ServicesController.php(969): Cake\ORM\Query->toArray()
#10 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Controller\Controller.php(440): App\Controller\ServicesController->eventinfo()
#11 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#12 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ServicesController))
#13 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\BaseApplication.php(78): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\RoutingMiddleware.php(59): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Routing\Middleware\AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#19 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\Middleware\ErrorHandlerMiddleware.php(92): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#21 C:\xampp\htdocs\meeat\vendor\cakephp\debug_kit\src\Middleware\DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#22 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#23 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#24 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Http\Server.php(80): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#25 C:\xampp\htdocs\meeat\webroot\index.php(37): Cake\Http\Server->run()
#26 {main}


2017-07-30 11:35:11 Error: Fatal Error (4): syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\meeat\src\Controller\ServicesController.php, line 1006]
Request URL: /services/getprofile
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 223
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 105
[main] - [internal], line ??



2017-07-30 11:35:12 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'else' (T_ELSE), expecting function (T_FUNCTION) in C:\xampp\htdocs\meeat\src\Controller\ServicesController.php on line 1006
Request URL: /services/getprofile
Stack Trace:
#0 C:\xampp\htdocs\meeat\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(105): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 1006)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


